---
title: "data manipulation"
author: "Xing Chen"
date: 2019-9-19
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


## import data files

```{r}
litters_data = read_csv("./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```


## selecting...

```{r}
select(litters_data, group, litter_number, starts_with("pups"))

select(litters_data, litter_number, group)

select(litters_data, litter_number, group, everything())

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

litters_select = select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, litter_number, GROUP = group)

rename(litters_data, Group = group)

litters_data
```

In larger datasets, I also use `starts_with()`, `ends_with()`, and `contains()` often.


## filtering.....

```{r, results='hide'}
filter(litters_data, group == "Con7")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, group %in% c("Con7", "Con8"))

filter(litters_data, gd0_weight + gd18_weight < 70)

# dont do this!
# filter(litters_data, !is.na(gd0_weight))

drop_na(litters_data)
drop_na(litters_data, gd0_weight)
```


